coverage:
  status:
    project:
      default:
        # allowed to drop X% and still result in a "success" commit status
        threshold: 0.05
    patch:
      default:
        # allowed to drop X% and still result in a "success" commit status
        threshold: 0.05
