repos:
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-simplify
