language: python
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "pypy-5.4.1"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"
env:
  global:
    - TEST='-v --durations 25'
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
    - SKIP_LATEX_BUILD=1
  matrix:
    - DOCUTILS=0.13.1
    - DOCUTILS=0.14
matrix:
  exclude:
    - python: "3.4"
      env: DOCUTILS=0.13.1
    - python: "3.5"
      env: DOCUTILS=0.13.1
    - python: "3.6"
      env: DOCUTILS=0.13.1
    - python: nightly
      env: DOCUTILS=0.13.1
    - python: "pypy-5.4.1"
      env: DOCUTILS=0.13.1
addons:
  apt:
    packages:
      - graphviz
      - imagemagick
install:
  - pip install -U pip setuptools
  - pip install docutils==$DOCUTILS
  - pip install -r test-reqs.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python3.6 -m pip install mypy typed-ast; fi
script:
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make type-check test-async; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then make test; fi
