language: python
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "pypy-5.4.1"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"

env:
  global:
    - TEST='-v --durations 25'
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
    - SKIP_LATEX_BUILD=1

addons:
  apt:
    packages:
      - graphviz
      - imagemagick

install:
  - pip install tox-travis

script:
  - tox
