name: Bug report
description: Something is not working correctly.
labels: "bug"

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce
      description: Please provide steps to reproduce this bug.
      value: |
        ```
        $ git clone https://github.com/.../some_project
        $ cd some_project
        $ pip install -r requirements.txt
        $ cd docs
        $ make html SPHINXOPTS="-D language=de"
        $ # open _build/html/index and see bla bla
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.

  - type: input
    attributes:
      label: Your project
      description: >-
        Link to your sphinx project, or attach zipped small project sample.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: >-
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Environment info

  - type: input
    attributes:
      label: OS
      description: >-
        [e.g. Unix/Linux/Mac/Win/other with version]
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
    validations:
      required: true
  - type: input
    attributes:
      label: Sphinx version
    validations:
      required: true
  - type: input
    attributes:
      label: Sphinx extensions
      description: >-
        [e.g. sphinx.ext.autodoc, recommonmark]
    validations:
      required: false
  - type: input
    attributes:
      label: Extra tools
      description: >-
        [e.g. Browser, tex or something else]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.
        [e.g. URL or Ticket]
