name: Coverage

on: [push]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sphinx-doc'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Check Python version
      run: python --version

    - name: Install graphviz
      run: sudo apt-get install graphviz

    - name: Install dependencies
      run: python -m pip install -U pip tox pytest-cov

    - name: Run Tox
      run: tox -e py -- -vv
      env:
        PYTEST_ADDOPTS: "--cov ./ --cov-append --cov-config pyproject.toml"
        VIRTUALENV_SYSTEM_SITE_PACKAGES: "1"

    - name: codecov
      uses: codecov/codecov-action@v3
