name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: flake8 --all-files

  isort:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: isort --all-files

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: mypy --all-files

  docs-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: sphinx-lint --all-files

  twine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine build
    - name: Lint with twine
      run: |
        python -m build .
        twine check dist/*
