name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install linting dependencies
      run: python -m pip install ".[lint]"

    - name: Lint with Ruff
      run: ruff check . --output-format github

    - name: Format with Ruff
      run: ruff format . --diff

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install linting dependencies
      run: python -m pip install ".[lint]"
    - name: Lint with flake8
      run: flake8 .

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install linting dependencies
      run: python -m pip install ".[lint]"
    - name: Install test dependencies to support type-checks
      run: python -m pip install ".[test]"
    - name: Type check with mypy
      run: mypy

  docs-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade sphinx-lint
    - name: Lint documentation with sphinx-lint
      run: make doclinter

  twine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade twine build
    - name: Lint with twine
      run: |
        python -m build .
        twine check dist/*
