name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [py35, py36, py37, py38, py39]
        os: [ubuntu-16.04]
        include:
        - name: py35
          python: 3.5
          docutils: du12
        - name: py36
          python: 3.6
          docutils: du13
        - name: py37
          python: 3.7
          docutils: du14
        - name: py38
          python: 3.8
          docutils: du15
        - name: py39
          python: 3.9
          docutils: du16
          coverage: "--cov ./ --cov-append --cov-config setup.cfg"
        - name: py310-dev
          python: 3.10-dev
          docutils: du16
          os: ubuntu-latest  # required
    env:
      PYTEST_ADDOPTS: ${{ matrix.coverage }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v1.0.0
      if: endsWith(matrix.python, '-dev')
      with:
        python-version: ${{ matrix.python }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Check Python version
      run: python --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: pip install -U tox codecov
    - name: Run Tox
      run: tox -e ${{ matrix.docutils }} -- -vv
    - name: codecov
      uses: codecov/codecov-action@v1
      if: matrix.coverage

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e py -- -vv
