name: CI on Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            architecture: x86
            python-version: 3.x
            toxenv: py
          - os: windows-latest
            architecture: x64
            python-version: 3.x
            toxenv: py
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        architecture: ${{ matrix.architecture }}
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e ${{ matrix.toxenv }} -- -vv
