name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    name: Python ${{ matrix.python }} (${{ matrix.docutils }})
    strategy:
      fail-fast: false
      matrix:
        include:
        - python: "3.6"
          docutils: du14
        - python: "3.7"
          docutils: du15
        - python: "3.8"
          docutils: du16
        - python: "3.9"
          docutils: du17
        - python: "3.10"
          docutils: du18
        - python: "3.10"
          docutils: du19
        - python: "3.11-dev"
          docutils: py311

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v2.1.1
      if: "endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: python -m pip install -U pip tox
    - name: Run Tox
      run: tox -e ${{ matrix.docutils }} -- -vv

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  python -m pip install -U pip tox
    - name: Run Tox
      run:  tox -e py -- -vv

  # https://github.com/marketplace/actions/alls-green#why
  check:  # This job does nothing and is only used for the branch protection

    if: always()

    needs:
    - ubuntu
    - windows

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
