name: CI (node.js)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 10.7

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - run: npm install
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm test
